apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-kuma
spec:
  selector:
    matchLabels:
      app: uptime-kuma
  template:
    metadata:
      labels:
        app: uptime-kuma
    spec:
      containers:
      - name: uptime-kuma
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 3001
        volumeMounts:
        - name: data
          mountPath: {{ .Values.persistence.path }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: uptime-kuma-pvc
