---
# Sets up a secret for cert-manager namespace to be able to use the cloudflare token
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cf-api-token
  namespace: default
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cf-api-token
    creationPolicy: Owner
  data:
    - secretKey: cf-api-token
      remoteRef:
        key: kv/cf-api-token
        property: token
