---
# Sets up a secret for alexprinter namespace to be able to use the cloudflare token
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alexprinter-secret
  namespace: alexprinter
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cf-token
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: kv/cloudflare
        property: token

---
# Sets up a secret for alexprinter namespace to be able to use the cloudflare token
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: alexprinter-secret
  namespace: argocd
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cf-token
    creationPolicy: Owner
  data:
    - secretKey: TUNNEL_TOKEN
      remoteRef:
        key: kv/cloudflare
        property: token
