services:
  consul:
    image: hashicorp/consul:1.19
    command:
      - agent
      - -server
      - -bootstrap-expect=1
      - -ui
      - -client=0.0.0.0
      - -bind=0.0.0.0
      - -data-dir=/consul/data
      - -config-dir=/consul/config
    ports:
      - "8500:8500"   # HTTP/UI
      - "8600:8600/udp" # DNS (optional)
    volumes:
      - /mnt/user/appdata/consul/data:/consul/data
      - /mnt/user/appdata/consul/config:/consul/config
    restart: unless-stopped
