apiVersion: v2
name: metallb-config
version: 0.1.0
description: MetalLB configuration for homelab
dependencies:
  - name: metallb
    version: ">=0.14.9"
    repository: https://metallb.github.io/metallb
