---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bmosan-com
  namespace: default
spec:
  secretName: bmosan-com-tls
  issuerRef:
    name: bmosan-cert
    kind: ClusterIssuer
  commonName: "*.bmosan.com"
  dnsNames:
  - "bmosan.com"
  - "*.bmosan.com"