---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: bmosan-cert
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bryanmorrison017@gmail.com
    privateKeySecretRef:
      name: bmosan-cert
    solvers:
      - dns01:
          cloudflare:
            email: bryanmorrison017@gmail.com
            apiTokenSecretRef:
              name: cf-api-token
              key: cf-api-token
        selector:
          dnsZones:
            - "bmosan.com"
            - "*.bmosan.com"
