$ cat templates/metallb_config.yaml
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: addr-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.3.100-192.168.3.199
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-default
  namespace: metallb-system
spec:
  ipAddressPools:
  - metallb-default
