image:
  repository: louislam/uptime-kuma
  tag: "2"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001
  targetPort: 3001

persistence:
  enabled: true
  storageClass: ""  # leave empty to use default
  accessMode: ReadWriteOnce
  size: 1Gi
